-- Sample knowledge base data for RAG
INSERT INTO knowledge_base (title, content, category) VALUES 
(
    'Mathematics - Basic Algebra',
    'Algebra is a branch of mathematics dealing with symbols and the rules for manipulating those symbols. In elementary algebra, those symbols (today written as Latin and Greek letters) represent quantities without fixed values, known as variables. The fundamental operations are addition, subtraction, multiplication, and division.',
    'mathematics'
),
(
    'Physics - Newton''s Laws of Motion',
    'Newton''s first law states that an object at rest stays at rest and an object in motion stays in motion with the same speed and in the same direction unless acted upon by an unbalanced force. The second law states that the acceleration of an object is directly proportional to the net force acting on it and inversely proportional to its mass (F = ma). The third law states that for every action, there is an equal and opposite reaction.',
    'physics'
),
(
    'Chemistry - Periodic Table',
    'The periodic table is a tabular arrangement of chemical elements, ordered by their atomic number, electron configuration, and recurring chemical properties. Elements in the same column (group) have similar chemical properties. The table has seven rows (periods) and eighteen columns (groups).',
    'chemistry'
),
(
    'Biology - Cell Structure',
    'All living organisms are composed of cells. Prokaryotic cells lack a membrane-bound nucleus, while eukaryotic cells have a nucleus enclosed by a nuclear membrane. Basic cell components include the cell membrane, cytoplasm, and genetic material (DNA). Plant cells also have a cell wall and chloroplasts.',
    'biology'
),
(
    'History - World War II',
    'World War II (1939-1945) was a global war involving most of the world''s nations. The main participants were the Axis powers (Germany, Italy, Japan) and the Allied powers (Britain, Soviet Union, United States, and others). The war ended with the defeat of the Axis powers and had profound consequences for global politics.',
    'history'
),
(
    'Literature - Shakespeare',
    'William Shakespeare (1564-1616) was an English playwright, poet, and actor, widely regarded as the greatest writer in the English language. His plays include tragedies (Hamlet, Macbeth, King Lear), comedies (A Midsummer Night''s Dream, Much Ado About Nothing), and histories (Henry V, Richard III).',
    'literature'
),
(
    'Computer Science - Algorithms',
    'An algorithm is a step-by-step procedure for solving a problem or completing a task. Common algorithmic paradigms include divide and conquer, dynamic programming, greedy algorithms, and brute force. Algorithm efficiency is measured using Big O notation, which describes worst-case time and space complexity.',
    'computer_science'
),
(
    'Geography - Climate Zones',
    'Earth has several major climate zones: tropical (hot and humid year-round), temperate (moderate temperatures with seasonal variation), polar (cold temperatures year-round), and arid (dry with little precipitation). Climate is influenced by latitude, altitude, ocean currents, and geographical features.',
    'geography'
);

-- Generate embeddings for the sample data (this would typically be done by the application)
-- For now, we'll add placeholder embeddings that would be generated by sentence transformers
-- In the actual implementation, these would be computed using the embedding service